### ISSUE TITLE
Why the sr_4 model can't enlarge the image?

### ISSUE THREAD

**Issue by Pumpkin0219** [ifryed/HyperRes#3]
I use generate_sr.py to generate LR images with HR images. And the used dataset is Set5. But when I run test_main.py, it turns out that the output sr image is still the same size as the lr image. How can I fix it? 
![QQ图片20240831170643](https://github.com/user-attachments/assets/5e3b0db2-9ded-4f8f-a1b1-960209153d5e)

**Comment by Pumpkin0219** [comment]
I found out that the conv5 can't transfer the image from 64 channels to 3 channels, but Idk why. The ModuleParallel's param is module of Conv2d(64, 3, kernel size=(3, 3),stride=(1, 1), padding=(1,1))

**Comment by ifryed** [comment]
The model does not resize the image internally. You take an image of size WxH and resize it by a factor of **x** then pass it through the network with the **x** as the correction factor. The model will correct the resizing artifacts as needed.

**Comment by Pumpkin0219** [comment]
> The model does not resize the image internally. You take an image of size WxH and resize it by a factor of **x** then pass it through the network with the **x** as the correction factor. The model will correct the resizing artifacts as needed.

Thanks for your reply! May I ask you the resize method? Cause I didn't run out the target psnr in your paper after I tried several resize methods. The method I use is img.resize(new_size, Image.ANTIALIAS)

**Comment by ifryed** [comment]
I use the **openCV** method with _Bicubic Interpolation_: [OpenCV resize docs](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#ga47a974309e9102f5f08231edc7e7529d)

`cv2.resize(img, size , interpolation=cv2.INTER_CUBIC)`

You can look at the [Live Demo](https://github.com/ifryed/HyperRes/blob/master/live_demo.py) code.
